In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [6]:
#Read the Data
dataframe=pd.read_csv('data.csv')

In [7]:
dataframe.head()

index    area  bathrooms     price    sq_price
0      0  2104.0        3.0  399900.0  190.066540
1      1  1600.0        3.0  329900.0  206.187500
2      2  2400.0        3.0  369000.0  153.750000
3      3  1416.0        2.0  232000.0  163.841808
4      4  3000.0        4.0  539900.0  179.966667

In [8]:
dataframe.describe()

index         area  bathrooms          price    sq_price
count  47.000000    47.000000  47.000000      47.000000   47.000000
mean   23.000000  2000.680851   3.170213  340412.659574  175.259506
std    13.711309   794.702354   0.760982  125039.899586   37.929278
min     0.000000   852.000000   1.000000  169900.000000  113.727721
25%    11.500000  1432.000000   3.000000  249900.000000  151.258519
50%    23.000000  1888.000000   3.000000  299900.000000  169.900000
75%    34.500000  2269.000000   4.000000  384450.000000  196.616621
max    46.000000  4478.000000   5.000000  699900.000000  318.587106

In [10]:
dataframe=dataframe.drop(['index','price','sq_price'],axis=1)

In [11]:
dataframe.head(2)

area  bathrooms
0  2104.0        3.0
1  1600.0        3.0

In [13]:
dataframe=dataframe[0:10]
dataframe

area  bathrooms
0  2104.0        3.0
1  1600.0        3.0
2  2400.0        3.0
3  1416.0        2.0
4  3000.0        4.0
5  1985.0        4.0
6  1534.0        3.0
7  1427.0        3.0
8  1380.0        3.0
9  1494.0        3.0

In [14]:
#Add labels to classify if house is a good buy or bad buy
#  1=Good Buy and 0=Bad Buy
dataframe.loc[:,('y1')]=[1,1,1,0,1,0,0,1,1,1]
#  y2 is negation of y1
dataframe.loc[:,('y2')]=dataframe['y1']==0
#  convert into 1and 0
dataframe.loc[:,('y2')]=dataframe['y2'].astype(int)
dataframe

area  bathrooms  y1  y2
0  2104.0        3.0   1   0
1  1600.0        3.0   1   0
2  2400.0        3.0   1   0
3  1416.0        2.0   0   1
4  3000.0        4.0   1   0
5  1985.0        4.0   0   1
6  1534.0        3.0   0   1
7  1427.0        3.0   1   0
8  1380.0        3.0   1   0
9  1494.0        3.0   1   0

In [19]:
# convert features and labels into tensors
inputX =dataframe.loc[:,['area','bathrooms']].values
inputY=dataframe.loc[:,['y1','y2']].values

In [20]:
inputX

array([[2.104e+03, 3.000e+00],
       [1.600e+03, 3.000e+00],
       [2.400e+03, 3.000e+00],
       [1.416e+03, 2.000e+00],
       [3.000e+03, 4.000e+00],
       [1.985e+03, 4.000e+00],
       [1.534e+03, 3.000e+00],
       [1.427e+03, 3.000e+00],
       [1.380e+03, 3.000e+00],
       [1.494e+03, 3.000e+00]])

In [21]:
inputY

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0]], dtype=int64)

In [22]:
#HYPERPARAMETERS
learning_rate=0.000001
training_epochs=2000
display_step=50
n_samples=inputY.size

In [27]:
x=tf.placeholder(tf.float32,[None,2])
W=tf.Variable(tf.zeros([2,2]))
b=tf.Variable(tf.zeros([2]))
y_values=tf.add(tf.matmul(x,W),b)
y=tf.nn.softmax(y_values)
y_=tf.placeholder(tf.float32,[None,2])

In [29]:
cost=tf.reduce_sum(tf.pow(y_ - y,2))/(2*n_samples)
optimizer=tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [30]:
init=tf.initialize_all_variables()
sess=tf.Session()
sess.run(init)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [46]:
for i in range(training_epochs):  
    sess.run(optimizer, feed_dict={x: inputX, y_: inputY}) # Take a gradient descent step using our inputs and labels

    # That's all! The rest of the cell just outputs debug messages. 
    # Display logs per epoch step
    if (i) % display_step == 0:
        cc = sess.run(cost, feed_dict={x: inputX, y_:inputY})
        print( "Training step:", '%04d' % (i), "cost=", '%.9f' %(cc))

print ("Optimization Finished!")
training_cost = sess.run(cost, feed_dict={x: inputX, y_: inputY})
print ("Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b)) 

Training step: 0000 cost= 0.101008393
Training step: 0050 cost= 0.101008393
Training step: 0100 cost= 0.101008393
Training step: 0150 cost= 0.101008393
Training step: 0200 cost= 0.101008378
Training step: 0250 cost= 0.101008378
Training step: 0300 cost= 0.101008378
Training step: 0350 cost= 0.101008371
Training step: 0400 cost= 0.101008371
Training step: 0450 cost= 0.101008371
Training step: 0500 cost= 0.101008371
Training step: 0550 cost= 0.101008371
Training step: 0600 cost= 0.101008356
Training step: 0650 cost= 0.101008356
Training step: 0700 cost= 0.101008348
Training step: 0750 cost= 0.101008348
Training step: 0800 cost= 0.101008333
Training step: 0850 cost= 0.101008333
Training step: 0900 cost= 0.101008333
Training step: 0950 cost= 0.101008333
Training step: 1000 cost= 0.101008333
Training step: 1050 cost= 0.101008318
Training step: 1100 cost= 0.101008318
Training step: 1150 cost= 0.101008318
Training step: 1200 cost= 0.101008318
Training step: 1250 cost= 0.101008311
Training ste

In [47]:
sess.run(y, feed_dict={x: inputX })

array([[0.73551995, 0.26448008],
       [0.6851762 , 0.3148238 ],
       [0.762564  , 0.23743607],
       [0.6655953 , 0.33440468],
       [0.81129795, 0.18870206],
       [0.72407454, 0.2759255 ],
       [0.6782105 , 0.3217895 ],
       [0.6667483 , 0.3332517 ],
       [0.66164947, 0.33835056],
       [0.6739497 , 0.3260503 ]], dtype=float32)

In [48]:
sess.run(tf.nn.softmax([1., 2.]))

array([0.26894143, 0.7310586 ], dtype=float32)